# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  turdproj_config = debug

else ifeq ($(config),release)
  turdproj_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := turdproj

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

turdproj:
ifneq (,$(turdproj_config))
	@echo "==== Building turdproj ($(turdproj_config)) ===="
	@${MAKE} --no-print-directory -C turdproj -f Makefile config=$(turdproj_config)
endif

clean:
	@${MAKE} --no-print-directory -C turdproj -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   turdproj"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"